model_list:
  - model_name: gemini-3-flash
    litellm_params:
      model: gemini/gemini-3-flash-preview
      api_key: os.environ/GEMINI_API_KEY
  - model_name: gemini-3-pro
    litellm_params:
      model: gemini/gemini-3.1-pro-preview
      api_key: os.environ/GEMINI_API_KEY
  - model_name: gemini-3-flash-lite
    litellm_params:
      model: gemini/gemini-3.1-flash-lite-preview
      api_key: os.environ/GEMINI_API_KEY
  - model_name: gemini-3-flash-image
    litellm_params:
      model: gemini/gemini-3.1-flash-image-preview
      api_key: os.environ/GEMINI_API_KEY
  - model_name: gemini-3-pro-image
    litellm_params:
      model: gemini/gemini-3-pro-image-preview
      api_key: os.environ/GEMINI_API_KEY

general_settings:
  drop_params: true
  allowed_openai_params: []

litellm_settings:
  drop_params: true
  num_retries: 0
